name: PR Manager Action

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
  schedule:
    - cron: '25 17 * * *'

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: My action
      uses: nk-gorbunoff/n7-action@master
      with: 
        slack_bot_auth_token: ${{ secrets.SLACK_BOT_AUTH_TOKEN }}
        slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
