name: PR Manager Action

on:
  schedule:
    - cron: '45,50,55 14 * * *'
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: My action
      uses: nk-gorbunoff/n7-action@master
      with: 
        slack_bot_auth_token: ${{ secrets.SLACK_BOT_AUTH_TOKEN }}
        slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pull_request_number: ${{ github.event.pull_request.number }}
