name: PR Manager Action

on:
  workflow_dispatch:

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Send Slack Notification
      uses: nk-gorbunoff/TestGithubAction@1.4
      with: 
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        github_trigger_event: ${{ github.event_name }}
